### ISSUE TITLE
Trigger sync event when specific file is added to the sync-folder 

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-storj#13]
This instead of having to wait 1 minute for it to sync the file.

**Comment by kaloyan-raev** [comment]
The challenge with triggering file upload to the Storj cloud is to determine when a file has finished copying. So far I've evaluated the [Java NIO2 File Watch Service](https://docs.oracle.com/javase/tutorial/essential/io/notification.html). Unfortunately, it is quite imperfect. If I copy a file to the Goobox folder, I get a `created` event at the start of copying and `modify` event at the end of copying. But `created` event can be fired when creating new empty file without a `modify` followup. If I just edit a file I can get one or more `modify` events. Copying of a file may also produce multiple `modify` events and it's hard to tell if you've got the final one.

The point is that I want avoid starting a file upload while the file is still copying into the folder. If this happens a partial, corrupted copy of the file will be uploaded. I can use some tricks and still use the standard Java File Watch Service, but before this I am going to evaluate a few other file watching libraries. Hopefully the will work better and this will make the implementation simpler and more robust.

List of open source libraries I've found so far:
- [Apache Commons IO Monitor](https://commons.apache.org/proper/commons-io/javadocs/api-release/index.html?org/apache/commons/io/monitor/package-summary.html)
- [jpathwatch](https://jpathwatch.wordpress.com/)
- [JNotify](http://jnotify.sourceforge.net/)
- [Directory Watcher](https://github.com/gmethvin/directory-watcher)
- [Perlock](https://github.com/danielmitterdorfer/perlock)

**Comment by MeijeSibbel** [comment]
Thanks for the update, its really important we get this right as we don't want to (1) waste the user's bandwidth and (2) make them wait for when synchronizing starts. It should all be snappy and responsive.

**Comment by kaloyan-raev** [comment]
I decided to go with the [Directory Watcher](https://github.com/gmethvin/directory-watcher) library. It promises better implementation for Mac OS X and registers recursive watches (i.e. for events in sub-directories) automatically.

It was not possible with any of the libraries to determine when a file copy is complete by just listening to the raw file events. Thus, I needed to implement a trick. If I get a file change event for a file, I add it to a map and store its latest file size. Every 3 seconds the file size is checked again. If the file size did not change, I assume that the file copy is complete.

Due to the above, the sync will be triggered within 3-5 seconds after the last file activity in the sync folder is recorded. It's not perfect, but I think it is good enough.

In addition, if a regular sync task is executed (after 1 minute of sleep), it will check if there are any ongoing file activity in the local sync folder. If there is, the sync will be delayed until the local file activity is completed. This is to avoid uploading partially copied files.
