### ISSUE TITLE
Set database folder as a hidden folder in windows or move it to Roaming/AppData

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-storj#21]
Currently the database folder is displayed in the user's home directory together with the actual sync folder, this makes things confusing and can cause accidents (e.g. dropping the files to the wrong folder, deleting the directory...), by hiding the folder only advanced users will be able to find it. Alternatively moving it to AppData under roaming would also be an option.

**Comment by kaloyan-raev** [comment]
OK. I can move the sync DB under the user's app data folder.

However, I don't think that the sync DB should be a "roaming" data. It's rather a "local" data. Meaning we should store it under `AppData\Local` instead of `AppData\Roaming`.

Here you can check the difference between "local" and "roaming" app data: https://superuser.com/a/150014

Agree?

**Comment by kaloyan-raev** [comment]
@MeijeSibbel do you agree with the above proposal - storing the db under "local" instead of "roaming" app data?

**Comment by MeijeSibbel** [comment]
Yes!, fine with me :)
