### ISSUE TITLE
Feature: Check for duplicate files 

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-storj#42]
A lot of times users will have the exact same file in multiple folders, uploading exact matching duplicates to the cloud  would be a waste of resources.

**Comment by kaloyan-raev** [comment]
So, you want to create a new bucket entry and associate it with the already uploaded shards of another bucket entry. Such an optimization should be done on the bridge level. There is currently no relevant API that we can use as a client.

Also note that such an optimization is a double-edged sword. It's true that it will safe storage and bandwidth. But you don't know the reason this file is duplicated. Perhaps, the user thought that this way she decreases the chance to lose the file due to lost shards. If this optimization is implemented then if one of the files cannot be retrieved, it would mean that all its duplicated copies are lost too.

**Comment by MeijeSibbel** [comment]
I agree, lets close this for now.
